# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nutri-fe
  namespace: pnt-quiz
  labels:
    app: nutri-fe
spec:
  selector:
    matchLabels:
      app: nutri-fe
      tier: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nutri-fe
        tier: frontend
    spec:
      containers:
        - name: nutri-fe
          image: 0xsera/nutri-fe:v0.0
          imagePullPolicy: Always
          ports:
            - protocol: TCP
              containerPort: 80
          resources:
            requests:
              memory: 250Mi
              cpu: 250m
            limits:
              memory: 500Mi
              cpu: 500m
          readinessProbe:
            httpGet:
              path: /
              port: 80
            successThreshold: 1
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /
              port: 80
            successThreshold: 1
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 1

---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nutri-fe
  labels:
    app: nutri-fe
spec:
  selector:
    app: nutri-fe
    tier: frontend
  type: LoadBalancer
  externalIPs:
    - 192.168.49.2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002

---
# hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nutri-fe
  labels:
    app: nutri-fe
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nutri-fe
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70